# Generated by Django 5.2.11 on 2026-03-02 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(blank=True, max_length=50, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='books')),
                ('photo_author', models.ImageField(blank=True, null=True, upload_to='books')),
                ('pages', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('retal_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('rental_period', models.IntegerField(blank=True, null=True)),
                ('inavialable', models.BooleanField(default=True)),
                ('status', models.CharField(blank=True, choices=[('available', 'Available'), ('rented', 'Rented'), ('sold', 'sold')], max_length=20, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lms_app.category')),
            ],
        ),
    ]
